[project]
name = "sigllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "orion-ml>=0.7.1",
    "tensorflow-gpu==2.6",
    "torch>=2.1.2",
]
